[package]
name = "wordle-player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5"
fancy-regex = "0.7"
rand = "0.8"
colored = "2"
csv = "1.1"
